environment:
  environment: dev
version: 1.0.{build}
branches:
  only:
    - master
init:
  - git config --global core.autocrlf input
install:
  - npm -g install npm@2
  - npm install -g gulp
  - npm install
  - nuget sources
nuget:
  account_feed: true
  disable_publish_on_pr: true
cache:
  - lib -> src\**\packages.config
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
after_build:
  - gulp package
build_script:  
  - gulp build  
test:
  assemblies:
    - specs\**\*.Specs.dll
artifacts:
  - path: deploy\CafePrintServer.*.zip
    name: server
notifications:
  - provider: Webhook
    url: http://appharborservicehookendpoint.apphb.com/build/appveyor/test
